name: demo
on:
  schedule:
    # every 15 minutes
    - cron: "*/60 * * * *"
  workflow_dispatch:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: azu/rss-to-twitter@v1
        with:
          # RSS feed URL
          RSS_URL: "https://kromiii.info/feed"
          TWEET_TEMPLATE: 'New Post: "%title%" %url%'
          UPDATE_WITHIN_MINUTES: 15
          # Twitter API Key
          TWITTER_APIKEY: ${{ secrets.APIKEY }}
          TWITTER_APIKEY_SECRET: ${{ secrets.APIKEY_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
